-- RAG layer for pedal manuals: chunked + embedded manual text for semantic
-- retrieval. Embeddings are gte-small (384 dims) generated by the Supabase
-- edge runtime's built-in model (see embed-manuals function).

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.manual_chunks (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pedal_id    uuid NOT NULL REFERENCES public.pedals(id) ON DELETE CASCADE,
  chunk_index int  NOT NULL,
  content     text NOT NULL,
  -- Hash of the source manual_text at embed time — lets the ingester skip
  -- pedals whose manual hasn't changed and purge stale chunks when it has.
  source_hash text NOT NULL,
  embedding   vector(384) NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (pedal_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS manual_chunks_embedding_idx
  ON public.manual_chunks USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS manual_chunks_pedal_idx
  ON public.manual_chunks (pedal_id);

ALTER TABLE public.manual_chunks ENABLE ROW LEVEL SECURITY;

-- Chunks derive from public catalog manuals — readable by anyone, writable
-- only by service role (the ingestion function).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'manual_chunks' AND policyname = 'Anyone can read manual chunks'
  ) THEN
    CREATE POLICY "Anyone can read manual chunks"
      ON public.manual_chunks FOR SELECT USING (true);
  END IF;
END $$;

-- Semantic search over chunks, optionally restricted to specific pedals.
CREATE OR REPLACE FUNCTION public.match_manual_chunks(
  query_embedding vector(384),
  match_count     int DEFAULT 8,
  filter_pedal_ids uuid[] DEFAULT NULL
)
RETURNS TABLE (
  pedal_id   uuid,
  content    text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    mc.pedal_id,
    mc.content,
    1 - (mc.embedding <=> query_embedding) AS similarity
  FROM manual_chunks mc
  WHERE filter_pedal_ids IS NULL OR mc.pedal_id = ANY(filter_pedal_ids)
  ORDER BY mc.embedding <=> query_embedding
  LIMIT match_count;
$$;

GRANT EXECUTE ON FUNCTION public.match_manual_chunks TO anon, authenticated, service_role;
